[package]
name = "toc-lsp-server"
version = "0.1.0"

authors.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
if_chain = "1.0.1"
lsp-types = "0.93.2"
serde_json = "1.0.64"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

toc-ide-db = { path = "../toc-ide-db" }
tokio = { version = "1.23.0", features = ["full"] }
tower-lsp = "0.17.0"
