[package]
name = "toc-lsp-server"
version = "0.1.0"
authors = ["DropDemBits <r3usrlnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
if_chain = "1.0.1"
lsp-server = "0.6.0"
lsp-types = "0.93.2"
serde_json = "1.0.64"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

toc-ide-db = { path = "../toc-ide-db" }