[package]
name = "toc-vfs-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc-span = { workspace = true }
toc-salsa = { workspace = true }
toc-vfs = { workspace = true }
camino = { workspace = true }
