[package]
name = "toc_vfs_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc_span = { path = "../toc_span" }
toc_salsa = { path = "../toc_salsa" }
toc_vfs = { path = "../toc_vfs" }
