status = [
    "build (ubuntu-latest, stable)",
    "build (windows-latest, stable)",
    "Check",
    "Rustfmt",
    "Docs",
    "Clippy"
]

delete_merged_branches = true
timeout_sec = 1200 # no longer than 20 minutes
use_squash_merge = false