[workspace]
resolver = "2"

members = ["xtask/", "lsp-server/", "compiler/*", "fuzzers/*"]

default-members = ["xtask/", "compiler/*", "lsp-server/"]

[workspace.dependencies]
itertools = "0.10.3"
indexmap = "1.7.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[profile.release]
debug = true

[patch.crates-io]
lazy_static = { git = "https://github.com/rust-fuzz/resettable-lazy-static.rs" }
