[workspace]
resolver = "2"

members = ["xtask/", "lsp-server/", "compiler/*", "fuzzers/*"]

default-members = ["xtask/", "compiler/*", "lsp-server/"]

[profile.release]
debug = true

# Uncomment when doing a fuzz campaign
#[patch.crates-io]
#lazy_static = { git = "https://github.com/rust-fuzz/resettable-lazy-static.rs" }
