[package]
name = "toc-syntax"
version = "0.1.0"

authors.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Local deps
toc-span = { workspace = true }
# External deps
rowan = "0.15"
num-derive = "^0.3"
num-traits = "0.2"
lexical = { version = "^6", default-features = false, features = [ "std", "parse-floats", ] }
thiserror = "1.0"