[package]
name = "toc-ide-db"
version = "0.1.0"

authors.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-types = { workspace = true }
tracing = { workspace = true }
camino = { workspace = true }
salsa = { workspace = true }
ropey = "1.5.0"

# Local compiler dependencies
toc-analysis = { workspace = true }
toc-ast-db = { workspace = true }
toc-hir = { workspace = true }
toc-hir-db = { workspace = true }
toc-hir-lowering = { workspace = true }
toc-paths = { workspace = true }
toc-reporting = { workspace = true }
toc-source-graph = { workspace = true }
toc-span = { workspace = true }
toc-vfs = { workspace = true }
toc-vfs-db = { workspace = true }
