[package]
name = "toc-ide-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-types = "0.93.2"
serde_json = "1.0.64"
tracing = { workspace = true }
camino = { workspace = true }
ropey = "1.5.0"

# Local compiler dependencies
toc-hir = { workspace = true }
toc-hir-db = { workspace = true }
toc-analysis = { workspace = true }
toc-ast-db = { workspace = true }
toc-reporting = { workspace = true }
toc-span = { workspace = true }
toc-vfs = { workspace = true }
toc-vfs-db = { workspace = true }
toc-salsa = { workspace = true }