[package]
name = "stackful-spec"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
either.workspace = true
indexmap.workspace = true
kdl = "6.2.2"
thiserror.workspace = true
miette.workspace = true
