[package]
name = "toc_hir_pretty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toc_hir = { path = "../toc_hir" }
toc_span = { path = "../toc_span" }
