//! Common interned symbols
#![allow(non_upper_case_globals)] // Keeping common names

use crate::symbol::Symbol;

lazy_static::lazy_static! {
    /// For unnamed definitions that can be generated by the user
    pub static ref Anonymous: Symbol = "<anonymous>".into();
    /// Name of the root of a translation unit
    pub static ref Root: Symbol = "<root>".into();
    /// For unnamed definitions that *can't* be generated by the user (e.g. unnamed parameters)
    pub static ref Unnamed: Symbol = "<unnamed>".into();
}
