name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        toolchain: [ stable ]
    env:
      RUSTDOCFLAGS: -D rustdoc::broken_intra_doc_links -D rustdoc::private_intra_doc_links
      # Disable debug info & incremental
      CARGO_PROFILE_DEV_DEBUG: false
      CARGO_PROFILE_TEST_DEBUG: false
      CARGO_INCREMENTAL: false

    steps:
    - uses: actions/checkout@v2

    - name: Install minimal ${{ matrix.toolchain }} toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        components: rustfmt
    - name: Setup cache
      uses: Swatinem/rust-cache@v1.2.0

    # Doing the actual work
    - name: Build
      run: cargo test --no-run --verbose
    - name: Run tests
      run: cargo test --verbose
    
    # Pre-merge section
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check docs
      run: cargo doc --workspace --no-deps
