name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        toolchain: [ stable ]
    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D broken_intra_doc_links -D private_intra_doc_links

    steps:
    - uses: actions/checkout@v2

    - name: Install minimal ${{ matrix.toolchain }} toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        components: rustfmt
    - name: Setup cache
      uses: Swatinem/rust-cache@v1.2.0

    # Doing the actual work
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check docs
      run: cargo doc
